config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: "pages#home"

  # post '/message' => 'messages#create'
  post '/mafia/:id' => 'mafias#create'
  # post '/rooms/:id' => 'messages#create'
  # post '/rooms/:id/messages' => 'rooms#messages', as: :messages_room
  get '/login' => "session#new"
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :mafias
  resources :rooms
  resources :messages
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :room, optional: true, dependent: :destroy
  validates :name, presence: true
  validates :password, presence: true, on: :create

  # has_many :gameStates, through: :rooms
  has_many :messages, dependent: :destroy
  has_many :mafium, dependent: :destroy
  serialize :stateobject

  # def update_current_users
  #     self.remainingPlayers = self.users.reject{ |p| p.id == @current_user.id }
  #     puts '#'*100
  #     self.save
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_if_logged_in, only: [:show]

  def new
  @user = User.new
end

def create
  user = User.create user_params

  if user.persisted?
    session[:user_id] = user.id
    image = Cloudinary::Uploader.upload(params[:file])
    user.image = image["public_id"]
    user.save

    redirect_to user_path(user.id)
  else
    flash[:errors] = user.errors.full_messages
    redirect_to new_user_path
  end
end

def index
end

def show
  @user = User.find params[:id]
end

def update
  if @current_user.update user_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @current_user.image = req["public_id"]
      @current_user.save
    end
    redirect_to user_path
  else
    flash[:errors] = @current_user.errors.full_messages
    redirect_to edit_user_path
  end

end

def edit
  @user = User.find params[:id]
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if flash[:errors] %>
<strong>Please correct the following errors:</strong>
<ol>
  <% flash[:errors].each do |e| %>
  <li><%= e %></li>
  <% end %>
</ol>
<% end %>


<div class="form-group userForm">
  <%= form_for(@user, :html => {:multipart => true}) do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name,class: "form-control one" %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password,class: "form-control one" %>
    <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation,class: "form-control one" %>
    <br>
    <% f.label :image %>
    <%= f.cl_image_upload :image,class: "form-control one"%>
    <br><br>
    <%= f.submit class:"btn btn-success"%>
  <% end %>
</div>

app/views/users/create.html.erb
<h2>Create an Account</h2>

<%= render partial: "form" %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h2 class="userForm">Edit <%= @user.name %></h2>
<br>
<%= link_to "Cancel", user_path, class:"btn btn-warning cancelButton"%>
<br>
<br>
<%= render partial: "form" %>

app/views/users/new.html.erb
<h2 class="userForm">Create an Account</h2>
<br>
<br>
<%= link_to "Cancel", login_path, class:"btn btn-warning cancelButton"%>
<br>
<br>
<%= render partial: "form" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<%= cl_image_tag(@current_user.image) %>

<%= link_to 'Please go to rooms', rooms_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>