config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: "pages#home"

  # post '/message' => 'messages#create'
  post '/mafia/:id' => 'mafias#create'
  # post '/rooms/:id' => 'messages#create'
  # post '/rooms/:id/messages' => 'rooms#messages', as: :messages_room
  get '/login' => "session#new"
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :mafias
  resources :rooms
  resources :messages
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :users
    has_many :messages, dependent: :destroy
    has_many :mafium, dependent: :destroy
    # has_many :gameStates, through: :users
    validates :name,:presence => true
    validates :name,:length => { :minimum => 2 }
    validates :name,uniqueness: true
    serialize :gamestate

    def start_game
      # room.start_game
        self.gamestate[:hasStarted] = true
        puts '+'*100
        # broadcast
        #    ActionCable.server.broadcast "room_#{ @room.id }_messages",
        #     action: 'GAME_START


        roles = {}

        # select the correct proportion of players to be mafia, randomly chosen
        self.users.sample((self.users.length/3).floor).each do |player|
            p 'hash', player.stateobject
            player.stateobject[:mafia] = true
            roles[player.id] = 'mafia';
            player.save
        end

        # remaining players are citizens
        self.users.each do |p|
            if !p.stateobject[:mafia]
                p.stateobject[:mafia] = false
                roles[p.id] = 'citizen';
                p.save
            end
        end

        self.users.each do |u|
            puts u.stateobject
            puts '2'*100
        end

        puts "=" * 100
        p roles

        # binding.pry

        self.gamestate[:roles] = roles
        self.save
        puts self.gamestate[:hasStarted]
        puts '3'*100
    end

    # def update_current_users
    #     self.remainingPlayers = self.users.reject{ |p| p.id == current_user.id }
    #     puts '#'*100
    #     self.save
    # end





end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :get_room, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logged_in

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @room.image = req["public_id"]
    end

    @room.save

    if @room.persisted?
      redirect_to rooms_path

    else
      flash[:errors] = @room.errors.full_messages
      redirect_to new_room_path
    end
  end

  def show
    @room = Room.find( params[:id] )
    # @room = Room.includes(:messages).find( params[:id] )
    @message = Message.new
    @mafia = Mafium.new
    @current_user.update( room_id: params[:id] )
    @current_user.update( stateobject: { mafia: nil, alive: true } )


    ActionCable.server.broadcast "room_#{ @room.id }_messages",
      action: 'PERSON_JOINED',
      name: @current_user.name,
      id: @current_user.id

    if @room.users.length > 2
      @room.update(gamestate: {
        canStart: true,
        hasStarted: false
      })
      # ActionCable.server.broadcast "room_#{ @room.id }_messages",
      #
      #   action: 'GAME_START',
      #   count: 5  # whatever other data you want

    else
      @room.update(gamestate: {
        canStart: false,
        hasStarted: false
      })
    end

    if @room.gamestate[:hasStarted]
      @room.users.sample((@room.users.length/3).floor).each do |player|
        player.stateobject[:mafia] = true
      end

      @room.users.each do |p|
        if !p.stateobject[:mafia]
          p.stateobject[:mafia] = false
        end
      end
    end

    # livingMafia = []
    # livingCitizens = []
    # @room.users.each do |p|
    #   if p.stateobject[:alive]
    #     if p.stateobject[:mafia]
    #       livingMafia.push(p)
    #     else
    #       livingCitizens.push(o)
    #     end
    #   end
    # end

    # def endingCheck()
    #   # check number of livng mafia and living citizens
    #   if livingMafia.length == 0
    #     return true
    #   elsif livingMafia.length > livingCitizens.length
    #     return true
    #   elsif livingMafia.length == 1 && livingCitizens.length == 1
    #     return true
    #   else
    #     return false
    #   end
    # end

  #   if @room.gamestate['hasStarted']

  #     @room.users.sample((@room.users.length/3).floor).each do |player|
  #       player.update(stateobject: { mafia: true})
  #     end
  #     @room.users.each do |p|
  #       if !p.stateobject['mafia']
  #         player.update(stateobject: { mafia: false})
  #       end
  #     end
  #   end
  #   # binding.pry
  #   livingMafia = []
  #   livingCitizens = []
  #   @room.users.each do |p|
  #     if p.stateobject['alive']
  #       if p.stateobject['mafia']
  #         livingMafia.push(p)
  #       else
  #         livingCitizens.push(o)
  #       end
  #     end
  #   end

  #   def endingCheck()
  #     # check number of livng mafia and living citizens
  #     if livingMafia.length == 0
  #       return true
  #     elsif livingMafia.length > livingCitizens.length
  #       return true
  #     elsif livingMafia.length == 1 && livingCitizens.length == 1
  #       return true
  #     else
  #       return false
  #     end
  #   end

  #   def dayTimer()
  #     timeTilDayEnd = 120
  #     while (timeTilDayEnd != 0)
  #       puts timeTilDayEnd
  #       sleep 1
  #       timeTilDayEnd = timeTilDayEnd-1
  #     end
  #   end

  #   def nightTimer()
  #     timeTilNightEnd = 30
  #     while (timeTilNightEnd != 0)
  #       puts timeTilNightEnd
  #       sleep 1
  #       timeTilNightEnd = timeTilNightEnd-1
  #     end
  #   end

  #   dayOrNight = -1

  #   loop do

  #     if (endingCheck())
  #       break
  #     end

  #     if dayOrNight > 0
  #       dayTimer()
  #     else
  #       nightTimer()
  #     end
  #     dayOrNight *= -1
  #   end

    dayOrNight = -1

  #   loop do
  #
  #     if (endingCheck())
  #       break
  #     end
  #
  #     if dayOrNight > 0
  #       dayTimer()
  #     else
  #       nightTimer()
  #     end
  #     dayOrNight *= -1
  #   end
  #
  end


  def broadcast
    ActionCable.server.broadcast 'messages',
      message: @message.text_body,
      user: @message.user.name
      head :ok
  end

  def index
    if @current_user.present?
      @rooms = Room.all
    else
      redirect_to root_path
    end
  end

  def edit


  end

  def update
    @room.update room_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @room.image = req["public_id"]
    end
    @room.update_attributes(room_params)
    @room.save
    redirect_to rooms_path
  end


  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:name, :description)
  end

  def get_room
    @room = Room.find params[:id]
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room, :html => {:multipart => true}) do |f| %>
<% if flash[:errors] %>
  <strong>The following errors need to be corrected :</strong>
  <ol>
    <% flash[:errors].each do |e| %>
    <li>
      <%= e %>
    </li>
    <% end %>
  </ol>
<% end %>

<div class="form-group row">
  <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :name %>
</label>
  <div class="col-sm-10">
  <%= f.text_field :name %>
  </div>
</div>
  <br>

  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label :description %>
</label>
    <div class="col-sm-10">
  <%= f.text_field :description %>
</div>
</div>
  <br>
  <div class="form-group row">
    <label for="colFormLabel" class="col-sm-2 col-form-label col-form-label-sm">
  <%= f.label "Room image: " %>
</label>
<div class="col-sm-10">
  <%= f.cl_image_upload :image %>
</div>
</div>
      <br>
      <br>
  <div class="col-sm-10">
  <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
  </div>

  <% end %>

app/views/rooms/edit.html.erb
<h1>Edit room <%= @room.name %></h1>
<%= render partial: "form" %>

app/views/rooms/index.html.erb
<script>
$('#joinGame').click(function(){
  console.log('joined game');
  // App.room_messages.send_message({
  //   event_type: 'start_game'
  //
  //  });
  return false;
 });
</script>


<h1>Rooms:</h1>

<% if @current_user.present? %>
<%= link_to 'Create new', new_room_path( @room ), class: "btn btn-success btn-block btn-sm buttonFont customButton" %>
<% end %>
<br>
<div class="container">
  <div class="row">
    <% @rooms.each do |e|%>
    <div class="col-lg-5 roomColumns">
      <span class: "roomName">
        <%= e.name %>
      </span>
       <div class="playersDisplay">
         <div class="playersDisplayTitle">Players Count</div>
         <%= e.users.length %>
       </div>
         <div class = "playButton">
           <%= link_to "Enter Room", room_path(e.id), class: "btn btn-success btn-block btn-sm buttonFont", id: "joinGame"%>
         </div>
    </div>
    <% end %>
  </div>
</div>
<br>
<br>

app/views/rooms/new.html.erb
<h1>Add your room</h1>
<%= render partial: "form" %>

app/views/rooms/show.html.erb
<script>
  const room_id = <%= @room.id %>;
  const user_id = <%= @current_user.id %>;
  const users = <%= @room.users.pluck(:id, :name).to_h.to_json.html_safe %>;
  $(document).ready(function(){



    $('#start').click(function(){
      console.log('clicked start');
      App.room_messages.send_message({
        event_type: 'start_game'

       });
      return false;
     });

    $('#exit_room').click(function(){
      console.log('clicked end');
      App.room_messages.send_message({
        event_type: 'remove_user',
      });
      return false;
    });

    let night = 20;
    nightTimer = setInterval(function(){
    night --;
    document.getElementById("timerNight").textContent = night;
    if(night <= 0)
        clearInterval(nightTimer);

    },1000);

    // let day = 120;
    // dayTimer = setInterval(function(){
    // day --;
    // document.getElementById("timerDay").textContent = day;
    // if(day <= 0)
    //     clearInterval(dayTimer);
    // },1000);



  });

</script>
<style>
  #mafia_chat_wrapper {
    display: none;
  }

  #timerNight{
    /* display: none; */
    text-align: right;
    font-size: 24px;
    margin-top:0px;
    color: blue;
  }

  #timerDay{
    display: none;
    text-align: right;
    font-size: 24px;
    margin-top:0px;
    color: red;
  }
  #pressure0{
    display: none;
    color:blue;
    font-size: 24px;
  }
  #pressure1{
    display: none;
    color:orange;
    font-size: 30px;
  }
  @keyframes pressure {
    from {background-color: blue;}
    to {background-color: red;}
  }
  @keyframes blink {
    from {opacity:1.0;}
    to {opacity: 0.0;}
  }

  #pressure2{
    color:orange;
    text-decoration: blink;
    animation-name: blink;
    animation-duration: 0.7s;
    animation-iteration-count: infinite;
    animation-timing-function: ease-in-out;
    animation-direction: alternate;
  }
  #timesup{
    display: none;
    color: red;
    font-size: 32px;
  }

</style>


<h1>Rooms <%= @room.name %></h1>
<br>
<br>
<div class="container">
  <div class="row">
    Players:
      <div id="playerlist"></div>

      </div>
</div>
<br>
<br>
<% if @room.image.present? %>
  <%= cl_image_tag @room.image, class: "img" %>
  <% end %>
<%# if @current_user.present? %>
<%#= link_to 'Edit', edit_room_path( @room ) %>
|
<%#= link_to 'Delete lol', room_path( @room ), method: 'delete' %>
<%# end %>
<br>
  <div class="col-sm-10">
    <% if @room.gamestate[:canStart] %>
     <%= button_tag "Start game", style: "display: show", class: "btn btn-danger btn-lg", id: "start"%>
    <% else %>
      <%= 'Not enough players to start' %>
    <% end %>
  </div>
<br>
<%# link_to "Back to Index", rooms_path, class: "btn btn-info btn-block btn-sm buttonFont customButton" %>

<% if flash[:errors] %>
  <strong>The following errors need to be corrected :</strong>
  <ol>
    <% flash[:errors].each do |e| %>
    <li>
      <%= e %>
    </li>
    <% end %>
  </ol>
<% end %>

<p> Kill poor citizens <span id="timerNight"> in 20 </span> Seconds</p>
<p id="pressure0">tic tac tic tac</p>
<p id="pressure1">Tic Tac Tic Tac</p>
<p id="pressure2">TIC TAC TIC TAC</p>
<p id="timesup">Time's up!!! Let's announce who got killed</p>


<p> ELIMINATE MAFIAAAA!!!!!!! <span id="timerDay"> in 120 </span> Seconds</p>


<div id="publicChannel">
  <h3>Messages:</h3>
  <div id="messages">
    <% @room.messages.each do |r| %>
      <b><%= r.user.name %>: </b><%= r.text_body %> <br></b><%= time_ago_in_words(r.created_at) %> <br>
    <% end %>
  </div>
  <br>

  <%= render partial: 'messages/message_form', locals:{room:@room, message: @message}%>

<br>
<div id="mafia_chat_wrapper">
  <%# if @current_user.stateobject[:mafia] %>
  <hr>
    <div id="privateChannel">
      <h4>Mafia channel:</h4>
      <div id="mafiaChannel">
        <% @room.mafium.each do |r| %>
          <b><%= r.user.name %>: </b><%= r.text_body %> <br></b><%= time_ago_in_words(r.created_at) %> <br>
        <% end %>
      </div>
    </div>
    <br>
    <%= render partial: 'mafias/mafia_form', locals:{room:@room, message: @mafia}%>
  <%# end %>
</div>

<%= link_to "Back to Rooms", rooms_path(id:"exit_room"), class: "btn btn-primary" %>