config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: "pages#home"

  # post '/message' => 'messages#create'
  post '/mafia/:id' => 'mafias#create'
  # post '/rooms/:id' => 'messages#create'
  # post '/rooms/:id/messages' => 'rooms#messages', as: :messages_room
  get '/login' => "session#new"
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :mafias
  resources :rooms
  resources :messages
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mafia Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= action_cable_meta_tag %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <h1></h1>
    <nav class="navbar-expand-lg navbar-light bg-light">

    <% if @current_user.present? %>

    <div class="nav-user nav navbar-nav navbar-left">
     <p>Welcome <strong><%= @current_user.name%>!</strong></p>&nbsp;&nbsp;&nbsp;&nbsp;
     <div class="text-left settingButton">
        <%= link_to "Setting", edit_user_path(@current_user), class: "btn btn-primary btn-block btn-sm buttonFont"%>
                        </div>&nbsp;&nbsp;&nbsp;&nbsp;
      <div class = "settingButton">
         <%= link_to "Log out", login_path, method: :delete, class: "btn btn-danger btn-block btn-sm buttonFont"%></div>&nbsp;&nbsp;&nbsp;&nbsp;
      </div>
   <% else %>

   <div class="nav-user nav navbar-nav navbar-left">
   <li class="nav-item">
     <%=link_to "Sign In", login_path, class: "btn btn-primary btn-block btn-sm buttonFont"%>
    </li>
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li class="nav-item">
     <%= link_to "Register", new_user_path, class: "btn btn-primary btn-block btn-sm buttonFont"%>
   </li>
  </div>
 <% end %>
 <ul class="nav nav-tabs">
   <li>
     <%= link_to "Home", root_path%><span class="sr-only">(current)</span></li>
     &nbsp;&nbsp;&nbsp;&nbsp;

     </ul>
</nav>
    <hr>

    <%= yield %>
  </body>
</html>